trigger:
- master

pr: none

pool:
  vmImage: 'Ubuntu-latest'

variables:
- group: swellbot-github
- group: 'Build Tools Skip Tokens'
- group: vsts-traffic-monitor

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- task: UseNode@1
  displayName: 'Use Node 8.x'
  inputs:
    version: 8.x

- script: |
    git checkout master
    git config user.name $(githubUser)
    git config user.email $(githubEmail)
    npm i
    npm run ext:package:ci
    git add package.json package-lock.json vss-extension.json task.json
    git commit -n -m "chore: Bumped to version $PACKAGE_VERSION from release pipeline $(succinctAllSkipTokens)"
    git push https://$(githubPat)@github.com/swellaby/vsts-traffic-monitor.git
    export PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version);")
    echo "##vso[task.setVariable variable=packageVersion]$PACKAGE_VERSION"
  displayName: 'Package extension'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: $(vsixArchiveName)
    targetPath: '$(Build.SourcesDirectory)/.vsix'
  displayName: 'Upload extension VSIX'

- task: ArchiveFiles@2
  displayName: 'Archive: full repo'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: tar
    archiveFile: '$(repoArchivePath)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: full repo'
  inputs:
    PathtoPublish: '$(repoArchivePath)'
    ArtifactName: '$(repoArtifactName)'
