trigger:
- master

pr: none

pool:
  vmImage: 'Ubuntu-18.04'

variables:
- group: swellbot-github
- group: 'Build Tools Skip Tokens'
- group: vsts-traffic-monitor

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- task: UseNode@1
  displayName: 'Use Node 10.x'
  inputs:
    version: 10.x

- template: 'steps/run-tests.yml'
  parameters:
    envName: 'CI'
    jobType: ''

- script: |
    bash <(curl -s https://codecov.io/bash) -t $(codecovToken)
  displayName: 'Publish coverage to Codecov'

- script: |
    git checkout master
    git config user.name $(githubUser)
    git config user.email $(githubEmail)
    npm run package-vsts-task-extension
    git add package.json package-lock.json vss-extension.json task.json
    git commit -n -m "chore: Bumped to version $PACKAGE_VERSION from release pipeline $(succinctAllSkipTokens)"
    git push https://$(githubPat)@github.com/swellaby/vsts-traffic-monitor.git
    export PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version);")
    echo "##vso[task.setVariable variable=packageVersion]$PACKAGE_VERSION"
  displayName: 'Package extension'

- template: templates/yml/any/sonar/run-sonar-cloud-cli-analysis.yml@templates
  parameters:
    projectVersion: $(packageVersion)

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: $(vsixArchiveName)
    targetPath: '$(Build.SourcesDirectory)/.vsix'
  displayName: 'Upload extension VSIX'

- task: ArchiveFiles@2
  displayName: 'Archive: full repo'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: tar
    archiveFile: '$(repoArchivePath)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: full repo'
  inputs:
    PathtoPublish: '$(repoArchivePath)'
    ArtifactName: '$(repoArtifactName)'
